// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Nest.proto

package io.github.mirrormingzz.mapstruct.protobuf.demo.domain;

public final class NestProtos {
  private NestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Nest1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Nest1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string a1 = 1;</code>
     */
    java.lang.String getA1();
    /**
     * <code>optional string a1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getA1Bytes();

    /**
     * <code>repeated .Nest2 nest2 = 2;</code>
     */
    java.util.List<io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2> 
        getNest2List();
    /**
     * <code>repeated .Nest2 nest2 = 2;</code>
     */
    io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 getNest2(int index);
    /**
     * <code>repeated .Nest2 nest2 = 2;</code>
     */
    int getNest2Count();
    /**
     * <code>repeated .Nest2 nest2 = 2;</code>
     */
    java.util.List<? extends io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2OrBuilder> 
        getNest2OrBuilderList();
    /**
     * <code>repeated .Nest2 nest2 = 2;</code>
     */
    io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2OrBuilder getNest2OrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Nest1}
   */
  public  static final class Nest1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Nest1)
      Nest1OrBuilder {
    // Use Nest1.newBuilder() to construct.
    private Nest1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Nest1() {
      a1_ = "";
      nest2_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Nest1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              a1_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                nest2_ = new java.util.ArrayList<io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2>();
                mutable_bitField0_ |= 0x00000002;
              }
              nest2_.add(
                  input.readMessage(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          nest2_ = java.util.Collections.unmodifiableList(nest2_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1.class, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1.Builder.class);
    }

    private int bitField0_;
    public static final int A1_FIELD_NUMBER = 1;
    private volatile java.lang.Object a1_;
    /**
     * <code>optional string a1 = 1;</code>
     */
    public java.lang.String getA1() {
      java.lang.Object ref = a1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        a1_ = s;
        return s;
      }
    }
    /**
     * <code>optional string a1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getA1Bytes() {
      java.lang.Object ref = a1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        a1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEST2_FIELD_NUMBER = 2;
    private java.util.List<io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2> nest2_;
    /**
     * <code>repeated .Nest2 nest2 = 2;</code>
     */
    public java.util.List<io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2> getNest2List() {
      return nest2_;
    }
    /**
     * <code>repeated .Nest2 nest2 = 2;</code>
     */
    public java.util.List<? extends io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2OrBuilder> 
        getNest2OrBuilderList() {
      return nest2_;
    }
    /**
     * <code>repeated .Nest2 nest2 = 2;</code>
     */
    public int getNest2Count() {
      return nest2_.size();
    }
    /**
     * <code>repeated .Nest2 nest2 = 2;</code>
     */
    public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 getNest2(int index) {
      return nest2_.get(index);
    }
    /**
     * <code>repeated .Nest2 nest2 = 2;</code>
     */
    public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2OrBuilder getNest2OrBuilder(
        int index) {
      return nest2_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getA1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, a1_);
      }
      for (int i = 0; i < nest2_.size(); i++) {
        output.writeMessage(2, nest2_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getA1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, a1_);
      }
      for (int i = 0; i < nest2_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, nest2_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1)) {
        return super.equals(obj);
      }
      io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 other = (io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1) obj;

      boolean result = true;
      result = result && getA1()
          .equals(other.getA1());
      result = result && getNest2List()
          .equals(other.getNest2List());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + A1_FIELD_NUMBER;
      hash = (53 * hash) + getA1().hashCode();
      if (getNest2Count() > 0) {
        hash = (37 * hash) + NEST2_FIELD_NUMBER;
        hash = (53 * hash) + getNest2List().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Nest1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Nest1)
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1.class, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1.Builder.class);
      }

      // Construct using io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNest2FieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        a1_ = "";

        if (nest2Builder_ == null) {
          nest2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          nest2Builder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest1_descriptor;
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 getDefaultInstanceForType() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1.getDefaultInstance();
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 build() {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 buildPartial() {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 result = new io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.a1_ = a1_;
        if (nest2Builder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            nest2_ = java.util.Collections.unmodifiableList(nest2_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.nest2_ = nest2_;
        } else {
          result.nest2_ = nest2Builder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1) {
          return mergeFrom((io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 other) {
        if (other == io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1.getDefaultInstance()) return this;
        if (!other.getA1().isEmpty()) {
          a1_ = other.a1_;
          onChanged();
        }
        if (nest2Builder_ == null) {
          if (!other.nest2_.isEmpty()) {
            if (nest2_.isEmpty()) {
              nest2_ = other.nest2_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureNest2IsMutable();
              nest2_.addAll(other.nest2_);
            }
            onChanged();
          }
        } else {
          if (!other.nest2_.isEmpty()) {
            if (nest2Builder_.isEmpty()) {
              nest2Builder_.dispose();
              nest2Builder_ = null;
              nest2_ = other.nest2_;
              bitField0_ = (bitField0_ & ~0x00000002);
              nest2Builder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNest2FieldBuilder() : null;
            } else {
              nest2Builder_.addAllMessages(other.nest2_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object a1_ = "";
      /**
       * <code>optional string a1 = 1;</code>
       */
      public java.lang.String getA1() {
        java.lang.Object ref = a1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          a1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string a1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getA1Bytes() {
        java.lang.Object ref = a1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          a1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a1 = 1;</code>
       */
      public Builder setA1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a1 = 1;</code>
       */
      public Builder clearA1() {
        
        a1_ = getDefaultInstance().getA1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a1 = 1;</code>
       */
      public Builder setA1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        a1_ = value;
        onChanged();
        return this;
      }

      private java.util.List<io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2> nest2_ =
        java.util.Collections.emptyList();
      private void ensureNest2IsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          nest2_ = new java.util.ArrayList<io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2>(nest2_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2OrBuilder> nest2Builder_;

      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public java.util.List<io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2> getNest2List() {
        if (nest2Builder_ == null) {
          return java.util.Collections.unmodifiableList(nest2_);
        } else {
          return nest2Builder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public int getNest2Count() {
        if (nest2Builder_ == null) {
          return nest2_.size();
        } else {
          return nest2Builder_.getCount();
        }
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 getNest2(int index) {
        if (nest2Builder_ == null) {
          return nest2_.get(index);
        } else {
          return nest2Builder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public Builder setNest2(
          int index, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 value) {
        if (nest2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNest2IsMutable();
          nest2_.set(index, value);
          onChanged();
        } else {
          nest2Builder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public Builder setNest2(
          int index, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder builderForValue) {
        if (nest2Builder_ == null) {
          ensureNest2IsMutable();
          nest2_.set(index, builderForValue.build());
          onChanged();
        } else {
          nest2Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public Builder addNest2(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 value) {
        if (nest2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNest2IsMutable();
          nest2_.add(value);
          onChanged();
        } else {
          nest2Builder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public Builder addNest2(
          int index, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 value) {
        if (nest2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNest2IsMutable();
          nest2_.add(index, value);
          onChanged();
        } else {
          nest2Builder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public Builder addNest2(
          io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder builderForValue) {
        if (nest2Builder_ == null) {
          ensureNest2IsMutable();
          nest2_.add(builderForValue.build());
          onChanged();
        } else {
          nest2Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public Builder addNest2(
          int index, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder builderForValue) {
        if (nest2Builder_ == null) {
          ensureNest2IsMutable();
          nest2_.add(index, builderForValue.build());
          onChanged();
        } else {
          nest2Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public Builder addAllNest2(
          java.lang.Iterable<? extends io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2> values) {
        if (nest2Builder_ == null) {
          ensureNest2IsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nest2_);
          onChanged();
        } else {
          nest2Builder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public Builder clearNest2() {
        if (nest2Builder_ == null) {
          nest2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          nest2Builder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public Builder removeNest2(int index) {
        if (nest2Builder_ == null) {
          ensureNest2IsMutable();
          nest2_.remove(index);
          onChanged();
        } else {
          nest2Builder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder getNest2Builder(
          int index) {
        return getNest2FieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2OrBuilder getNest2OrBuilder(
          int index) {
        if (nest2Builder_ == null) {
          return nest2_.get(index);  } else {
          return nest2Builder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public java.util.List<? extends io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2OrBuilder> 
           getNest2OrBuilderList() {
        if (nest2Builder_ != null) {
          return nest2Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nest2_);
        }
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder addNest2Builder() {
        return getNest2FieldBuilder().addBuilder(
            io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.getDefaultInstance());
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder addNest2Builder(
          int index) {
        return getNest2FieldBuilder().addBuilder(
            index, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.getDefaultInstance());
      }
      /**
       * <code>repeated .Nest2 nest2 = 2;</code>
       */
      public java.util.List<io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder> 
           getNest2BuilderList() {
        return getNest2FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2OrBuilder> 
          getNest2FieldBuilder() {
        if (nest2Builder_ == null) {
          nest2Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2OrBuilder>(
                  nest2_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          nest2_ = null;
        }
        return nest2Builder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Nest1)
    }

    // @@protoc_insertion_point(class_scope:Nest1)
    private static final io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1();
    }

    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Nest1>
        PARSER = new com.google.protobuf.AbstractParser<Nest1>() {
      public Nest1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Nest1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Nest1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Nest1> getParserForType() {
      return PARSER;
    }

    public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Nest2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Nest2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string a2 = 1;</code>
     */
    java.lang.String getA2();
    /**
     * <code>optional string a2 = 1;</code>
     */
    com.google.protobuf.ByteString
        getA2Bytes();

    /**
     * <code>optional .Nest3 nest3 = 2;</code>
     */
    boolean hasNest3();
    /**
     * <code>optional .Nest3 nest3 = 2;</code>
     */
    io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 getNest3();
    /**
     * <code>optional .Nest3 nest3 = 2;</code>
     */
    io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3OrBuilder getNest3OrBuilder();
  }
  /**
   * Protobuf type {@code Nest2}
   */
  public  static final class Nest2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Nest2)
      Nest2OrBuilder {
    // Use Nest2.newBuilder() to construct.
    private Nest2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Nest2() {
      a2_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Nest2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              a2_ = s;
              break;
            }
            case 18: {
              io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.Builder subBuilder = null;
              if (nest3_ != null) {
                subBuilder = nest3_.toBuilder();
              }
              nest3_ = input.readMessage(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(nest3_);
                nest3_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.class, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder.class);
    }

    public static final int A2_FIELD_NUMBER = 1;
    private volatile java.lang.Object a2_;
    /**
     * <code>optional string a2 = 1;</code>
     */
    public java.lang.String getA2() {
      java.lang.Object ref = a2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        a2_ = s;
        return s;
      }
    }
    /**
     * <code>optional string a2 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getA2Bytes() {
      java.lang.Object ref = a2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        a2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEST3_FIELD_NUMBER = 2;
    private io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 nest3_;
    /**
     * <code>optional .Nest3 nest3 = 2;</code>
     */
    public boolean hasNest3() {
      return nest3_ != null;
    }
    /**
     * <code>optional .Nest3 nest3 = 2;</code>
     */
    public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 getNest3() {
      return nest3_ == null ? io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.getDefaultInstance() : nest3_;
    }
    /**
     * <code>optional .Nest3 nest3 = 2;</code>
     */
    public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3OrBuilder getNest3OrBuilder() {
      return getNest3();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getA2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, a2_);
      }
      if (nest3_ != null) {
        output.writeMessage(2, getNest3());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getA2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, a2_);
      }
      if (nest3_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getNest3());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2)) {
        return super.equals(obj);
      }
      io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 other = (io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2) obj;

      boolean result = true;
      result = result && getA2()
          .equals(other.getA2());
      result = result && (hasNest3() == other.hasNest3());
      if (hasNest3()) {
        result = result && getNest3()
            .equals(other.getNest3());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + A2_FIELD_NUMBER;
      hash = (53 * hash) + getA2().hashCode();
      if (hasNest3()) {
        hash = (37 * hash) + NEST3_FIELD_NUMBER;
        hash = (53 * hash) + getNest3().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Nest2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Nest2)
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.class, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.Builder.class);
      }

      // Construct using io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        a2_ = "";

        if (nest3Builder_ == null) {
          nest3_ = null;
        } else {
          nest3_ = null;
          nest3Builder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest2_descriptor;
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 getDefaultInstanceForType() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.getDefaultInstance();
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 build() {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 buildPartial() {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 result = new io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2(this);
        result.a2_ = a2_;
        if (nest3Builder_ == null) {
          result.nest3_ = nest3_;
        } else {
          result.nest3_ = nest3Builder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2) {
          return mergeFrom((io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 other) {
        if (other == io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2.getDefaultInstance()) return this;
        if (!other.getA2().isEmpty()) {
          a2_ = other.a2_;
          onChanged();
        }
        if (other.hasNest3()) {
          mergeNest3(other.getNest3());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object a2_ = "";
      /**
       * <code>optional string a2 = 1;</code>
       */
      public java.lang.String getA2() {
        java.lang.Object ref = a2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          a2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string a2 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getA2Bytes() {
        java.lang.Object ref = a2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          a2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a2 = 1;</code>
       */
      public Builder setA2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a2 = 1;</code>
       */
      public Builder clearA2() {
        
        a2_ = getDefaultInstance().getA2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a2 = 1;</code>
       */
      public Builder setA2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        a2_ = value;
        onChanged();
        return this;
      }

      private io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 nest3_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.Builder, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3OrBuilder> nest3Builder_;
      /**
       * <code>optional .Nest3 nest3 = 2;</code>
       */
      public boolean hasNest3() {
        return nest3Builder_ != null || nest3_ != null;
      }
      /**
       * <code>optional .Nest3 nest3 = 2;</code>
       */
      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 getNest3() {
        if (nest3Builder_ == null) {
          return nest3_ == null ? io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.getDefaultInstance() : nest3_;
        } else {
          return nest3Builder_.getMessage();
        }
      }
      /**
       * <code>optional .Nest3 nest3 = 2;</code>
       */
      public Builder setNest3(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 value) {
        if (nest3Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nest3_ = value;
          onChanged();
        } else {
          nest3Builder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Nest3 nest3 = 2;</code>
       */
      public Builder setNest3(
          io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.Builder builderForValue) {
        if (nest3Builder_ == null) {
          nest3_ = builderForValue.build();
          onChanged();
        } else {
          nest3Builder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Nest3 nest3 = 2;</code>
       */
      public Builder mergeNest3(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 value) {
        if (nest3Builder_ == null) {
          if (nest3_ != null) {
            nest3_ =
              io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.newBuilder(nest3_).mergeFrom(value).buildPartial();
          } else {
            nest3_ = value;
          }
          onChanged();
        } else {
          nest3Builder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Nest3 nest3 = 2;</code>
       */
      public Builder clearNest3() {
        if (nest3Builder_ == null) {
          nest3_ = null;
          onChanged();
        } else {
          nest3_ = null;
          nest3Builder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Nest3 nest3 = 2;</code>
       */
      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.Builder getNest3Builder() {
        
        onChanged();
        return getNest3FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Nest3 nest3 = 2;</code>
       */
      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3OrBuilder getNest3OrBuilder() {
        if (nest3Builder_ != null) {
          return nest3Builder_.getMessageOrBuilder();
        } else {
          return nest3_ == null ?
              io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.getDefaultInstance() : nest3_;
        }
      }
      /**
       * <code>optional .Nest3 nest3 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.Builder, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3OrBuilder> 
          getNest3FieldBuilder() {
        if (nest3Builder_ == null) {
          nest3Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.Builder, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3OrBuilder>(
                  getNest3(),
                  getParentForChildren(),
                  isClean());
          nest3_ = null;
        }
        return nest3Builder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Nest2)
    }

    // @@protoc_insertion_point(class_scope:Nest2)
    private static final io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2();
    }

    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Nest2>
        PARSER = new com.google.protobuf.AbstractParser<Nest2>() {
      public Nest2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Nest2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Nest2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Nest2> getParserForType() {
      return PARSER;
    }

    public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Nest3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Nest3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string a3 = 1;</code>
     */
    java.lang.String getA3();
    /**
     * <code>optional string a3 = 1;</code>
     */
    com.google.protobuf.ByteString
        getA3Bytes();
  }
  /**
   * Protobuf type {@code Nest3}
   */
  public  static final class Nest3 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Nest3)
      Nest3OrBuilder {
    // Use Nest3.newBuilder() to construct.
    private Nest3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Nest3() {
      a3_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Nest3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              a3_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest3_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.class, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.Builder.class);
    }

    public static final int A3_FIELD_NUMBER = 1;
    private volatile java.lang.Object a3_;
    /**
     * <code>optional string a3 = 1;</code>
     */
    public java.lang.String getA3() {
      java.lang.Object ref = a3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        a3_ = s;
        return s;
      }
    }
    /**
     * <code>optional string a3 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getA3Bytes() {
      java.lang.Object ref = a3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        a3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getA3Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, a3_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getA3Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, a3_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3)) {
        return super.equals(obj);
      }
      io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 other = (io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3) obj;

      boolean result = true;
      result = result && getA3()
          .equals(other.getA3());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + A3_FIELD_NUMBER;
      hash = (53 * hash) + getA3().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Nest3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Nest3)
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest3_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.class, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.Builder.class);
      }

      // Construct using io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        a3_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.internal_static_Nest3_descriptor;
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 getDefaultInstanceForType() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.getDefaultInstance();
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 build() {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 buildPartial() {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 result = new io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3(this);
        result.a3_ = a3_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3) {
          return mergeFrom((io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 other) {
        if (other == io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3.getDefaultInstance()) return this;
        if (!other.getA3().isEmpty()) {
          a3_ = other.a3_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object a3_ = "";
      /**
       * <code>optional string a3 = 1;</code>
       */
      public java.lang.String getA3() {
        java.lang.Object ref = a3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          a3_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string a3 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getA3Bytes() {
        java.lang.Object ref = a3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          a3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a3 = 1;</code>
       */
      public Builder setA3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a3 = 1;</code>
       */
      public Builder clearA3() {
        
        a3_ = getDefaultInstance().getA3();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a3 = 1;</code>
       */
      public Builder setA3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        a3_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Nest3)
    }

    // @@protoc_insertion_point(class_scope:Nest3)
    private static final io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3();
    }

    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Nest3>
        PARSER = new com.google.protobuf.AbstractParser<Nest3>() {
      public Nest3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Nest3(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Nest3> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Nest3> getParserForType() {
      return PARSER;
    }

    public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.NestProtos.Nest3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Nest1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Nest1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Nest2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Nest2_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Nest3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Nest3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nNest.proto\"*\n\005Nest1\022\n\n\002a1\030\001 \001(\t\022\025\n\005nes" +
      "t2\030\002 \003(\0132\006.Nest2\"*\n\005Nest2\022\n\n\002a2\030\001 \001(\t\022\025\n" +
      "\005nest3\030\002 \001(\0132\006.Nest3\"\023\n\005Nest3\022\n\n\002a3\030\001 \001(" +
      "\tBC\n5io.github.mirrormingzz.mapstruct.pr" +
      "otobuf.demo.domainB\nNestProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Nest1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Nest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Nest1_descriptor,
        new java.lang.String[] { "A1", "Nest2", });
    internal_static_Nest2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Nest2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Nest2_descriptor,
        new java.lang.String[] { "A2", "Nest3", });
    internal_static_Nest3_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Nest3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Nest3_descriptor,
        new java.lang.String[] { "A3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
