// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package io.github.mirrormingzz.mapstruct.protobuf.demo.domain;

public final class TestProtos {
  private TestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Test)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string a1 = 1;</code>
     */
    java.lang.String getA1();
    /**
     * <code>optional string a1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getA1Bytes();

    /**
     * <code>optional string a2 = 2;</code>
     */
    java.lang.String getA2();
    /**
     * <code>optional string a2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getA2Bytes();

    /**
     * <code>optional string a3 = 3;</code>
     */
    java.lang.String getA3();
    /**
     * <code>optional string a3 = 3;</code>
     */
    com.google.protobuf.ByteString
        getA3Bytes();
  }
  /**
   * Protobuf type {@code Test}
   */
  public  static final class Test extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Test)
      TestOrBuilder {
    // Use Test.newBuilder() to construct.
    private Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test() {
      a1_ = "";
      a2_ = "";
      a3_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Test(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              a1_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              a2_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              a3_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.internal_static_Test_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.internal_static_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test.class, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test.Builder.class);
    }

    public static final int A1_FIELD_NUMBER = 1;
    private volatile java.lang.Object a1_;
    /**
     * <code>optional string a1 = 1;</code>
     */
    public java.lang.String getA1() {
      java.lang.Object ref = a1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        a1_ = s;
        return s;
      }
    }
    /**
     * <code>optional string a1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getA1Bytes() {
      java.lang.Object ref = a1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        a1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int A2_FIELD_NUMBER = 2;
    private volatile java.lang.Object a2_;
    /**
     * <code>optional string a2 = 2;</code>
     */
    public java.lang.String getA2() {
      java.lang.Object ref = a2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        a2_ = s;
        return s;
      }
    }
    /**
     * <code>optional string a2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getA2Bytes() {
      java.lang.Object ref = a2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        a2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int A3_FIELD_NUMBER = 3;
    private volatile java.lang.Object a3_;
    /**
     * <code>optional string a3 = 3;</code>
     */
    public java.lang.String getA3() {
      java.lang.Object ref = a3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        a3_ = s;
        return s;
      }
    }
    /**
     * <code>optional string a3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getA3Bytes() {
      java.lang.Object ref = a3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        a3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getA1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, a1_);
      }
      if (!getA2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, a2_);
      }
      if (!getA3Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, a3_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getA1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, a1_);
      }
      if (!getA2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, a2_);
      }
      if (!getA3Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, a3_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test)) {
        return super.equals(obj);
      }
      io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test other = (io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test) obj;

      boolean result = true;
      result = result && getA1()
          .equals(other.getA1());
      result = result && getA2()
          .equals(other.getA2());
      result = result && getA3()
          .equals(other.getA3());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + A1_FIELD_NUMBER;
      hash = (53 * hash) + getA1().hashCode();
      hash = (37 * hash) + A2_FIELD_NUMBER;
      hash = (53 * hash) + getA2().hashCode();
      hash = (37 * hash) + A3_FIELD_NUMBER;
      hash = (53 * hash) + getA3().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Test)
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.TestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.internal_static_Test_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.internal_static_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test.class, io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test.Builder.class);
      }

      // Construct using io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        a1_ = "";

        a2_ = "";

        a3_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.internal_static_Test_descriptor;
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test getDefaultInstanceForType() {
        return io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test.getDefaultInstance();
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test build() {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test buildPartial() {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test result = new io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test(this);
        result.a1_ = a1_;
        result.a2_ = a2_;
        result.a3_ = a3_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test) {
          return mergeFrom((io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test other) {
        if (other == io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test.getDefaultInstance()) return this;
        if (!other.getA1().isEmpty()) {
          a1_ = other.a1_;
          onChanged();
        }
        if (!other.getA2().isEmpty()) {
          a2_ = other.a2_;
          onChanged();
        }
        if (!other.getA3().isEmpty()) {
          a3_ = other.a3_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object a1_ = "";
      /**
       * <code>optional string a1 = 1;</code>
       */
      public java.lang.String getA1() {
        java.lang.Object ref = a1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          a1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string a1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getA1Bytes() {
        java.lang.Object ref = a1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          a1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a1 = 1;</code>
       */
      public Builder setA1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a1 = 1;</code>
       */
      public Builder clearA1() {
        
        a1_ = getDefaultInstance().getA1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a1 = 1;</code>
       */
      public Builder setA1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        a1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object a2_ = "";
      /**
       * <code>optional string a2 = 2;</code>
       */
      public java.lang.String getA2() {
        java.lang.Object ref = a2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          a2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string a2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getA2Bytes() {
        java.lang.Object ref = a2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          a2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a2 = 2;</code>
       */
      public Builder setA2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a2 = 2;</code>
       */
      public Builder clearA2() {
        
        a2_ = getDefaultInstance().getA2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a2 = 2;</code>
       */
      public Builder setA2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        a2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object a3_ = "";
      /**
       * <code>optional string a3 = 3;</code>
       */
      public java.lang.String getA3() {
        java.lang.Object ref = a3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          a3_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string a3 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getA3Bytes() {
        java.lang.Object ref = a3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          a3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a3 = 3;</code>
       */
      public Builder setA3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a3 = 3;</code>
       */
      public Builder clearA3() {
        
        a3_ = getDefaultInstance().getA3();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a3 = 3;</code>
       */
      public Builder setA3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        a3_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Test)
    }

    // @@protoc_insertion_point(class_scope:Test)
    private static final io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test();
    }

    public static io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test>
        PARSER = new com.google.protobuf.AbstractParser<Test>() {
      public Test parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Test(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test> getParserForType() {
      return PARSER;
    }

    public io.github.mirrormingzz.mapstruct.protobuf.demo.domain.TestProtos.Test getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTest.proto\"*\n\004Test\022\n\n\002a1\030\001 \001(\t\022\n\n\002a2\030\002" +
      " \001(\t\022\n\n\002a3\030\003 \001(\tBC\n5io.github.mirrorming" +
      "zz.mapstruct.protobuf.demo.domainB\nTestP" +
      "rotosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Test_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test_descriptor,
        new java.lang.String[] { "A1", "A2", "A3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
